export const FriendsProfileData = [
    {
        name: 'Ram_che',
        accountName: 'chxxwn',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:651,
        following:88,
        follow:false,
    },
    {
        name: 'Ram_che',
        accountName: 'chxxwn',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:6543,
        following:143,
        follow:false,
    },{
        name: 'Tomas',
        accountName: 'tomntomas',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:6543,
        following:43,
        follow:false,
    },{
        name: 'ggggg',
        accountName: 'chxxwn',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:6543,
        following:43,
        follow:false,
    },{
        name: 'dgee',
        accountName: 'michin',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:4211,
        following:43,
        follow:false,
    },{
        name: 'Ram_che',
        accountName: 'chxxwn',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:633,
        following:983,
        follow:false,
    },{
        name: 'chicken_master',
        accountName: 'chickmaster',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:655,
        following:432,
        follow:false,
    },{
        name: 'Ram_che',
        accountName: 'chxxwn',
        profileImage: require('../../storage/images/userImage.jpeg'),
        posts:56,
        followers:6543,
        following:43,
        follow:false,
    },
]